// Expected English strings from contract section 10.
export const S = {
  "app.title.myRequests": "My requests",
  "header.mode.personal": "midPoint sees everything here as {name}, this server's own account.",
  "header.mode.personal.help": "This server signs in to midPoint with its configured account, so midPoint sees that account on every request, whoever is using the assistant.",
  "header.sharedCredential": "This server signs in to midPoint with a shared account, {name}, so it can't show what's yours.",
  "common.refresh": "Refresh",
  "common.refreshing": "Refreshing…",
  "common.asOf": "As of {time}",
  "common.askAssistantToRefresh": "To update this view, ask the assistant to run it again.",
  "common.readOnlyHost": "This app can show this view but not act from it. To make changes, ask the assistant.",
  "common.expand": "Expand",
  "common.collapse": "Exit full screen",
  "common.cancel": "Cancel",
  "common.showDetails": "Show technical details",
  "common.hideDetails": "Hide technical details",
  "common.showMore": "Show more",
  "common.showLess": "Show less",
  "common.andMore": "{count, plural, one {# more} other {# more}}",
  "common.whatsThis": "What's this?",
  "common.you": "you",
  "common.personHidden": "a person you can't see in midPoint",
  "common.personHiddenStart": "A person you can't see in midPoint",
  "common.itemHidden": "an item you can't see in midPoint",
  "common.request": "the request",
  "common.inherited": "Comes with other access",
  "common.inheritedVia": "Comes with {source}",
  "common.detailsTool": "Tool: {tool}",
  "common.redacted": "[address removed]",
  "common.openInMidpoint": "Open in midPoint",
  "common.openInMidpointLabel": "Open in midPoint: {name}",
  "common.openInMidpointNote": "\"Open in midPoint\" opens midPoint's own pages. You may need to sign in there, and some pages need midPoint permissions you might not have.",
  "state.slow": "Still waiting for midPoint…",
  "state.cancelled": "This request was cancelled.",
  "state.cancelledReason": "This request was cancelled: {reason}",
  "state.versionMismatch": "This view doesn't match the server's version. The server's answer is shown as text below.",
  "state.textOnly": "This answer can't be shown as a view. Here is the server's text.",
  "dryrun.banner.title": "Preview only",
  "dryrun.banner.body": "Changes are turned off on this server. Buttons show what would be sent to midPoint; nothing is changed.",
  "dryrun.submit": "Show preview",
  "dryrun.result.title": "Preview: nothing was changed",
  "dryrun.details.request": "Request that would be sent",
  "dryrun.details.summary": "Server summary: {summary}",
  "strip.source": "Reported by {source}",
  "strip.sourceUnnamed": "Reported by the connection between the assistant and midPoint",
  "strip.held.title": "Waiting for approval",
  "strip.held.body": "This action is waiting for approval by {approver}. It hasn't reached midPoint yet.",
  "strip.held.bodyNoApprover": "This action is waiting for approval. It hasn't reached midPoint yet.",
  "strip.denied.title": "Blocked",
  "strip.denied.body": "This action was blocked before it reached midPoint.",
  "strip.reason": "Reason: {reason}",
  "strip.expires": "Expires {time}",
  "strip.ref": "Reference: {ref}",
  "confirm.row.role": "Role",
  "confirm.row.for": "For",
  "confirm.row.from": "From",
  "confirm.row.request": "Request",
  "confirm.row.validity": "How long",
  "confirm.working": "Working…",
  "confirm.withdraw.title": "Withdraw this request?",
  "confirm.withdraw.body": "Your request for {role} for {user} will be closed in midPoint, and its open approval steps cancelled.",
  "confirm.withdraw.bodySelf": "Your request for {role} will be closed in midPoint, and its open approval steps cancelled.",
  "confirm.withdraw.submit": "Withdraw request",
  "error.generic": "midPoint couldn't complete this.",
  "error.sharedCredential": "This server signs in to midPoint with a shared account, so it can't answer for you personally. Ask your midPoint administrator to set up per-person sign-in.",
  "error.notRequestable": "This role can't be requested: midPoint's catalog doesn't offer it for request.",
  "error.invalidField": "Some request details are missing or not valid. Check the marked field.",
  "error.invalidValidity": "The chosen dates aren't valid. Check how long the role should be valid and try again.",
  "error.notInInbox": "This request is no longer waiting for your decision.",
  "error.alreadyDecided": "This step of the request has already been decided.",
  "error.requestClosed": "This request is already closed: it was decided or withdrawn.",
  "error.notYourRequest": "Only the person who made a request can withdraw it.",
  "error.notAssigned": "This role is no longer directly assigned to this person.",
  "error.invalidInput": "The server rejected the request as incomplete or invalid.",
  "error.notAuthorized": "midPoint says you aren't allowed to do this.",
  "error.notFound": "midPoint couldn't find this item. It may have been deleted.",
  "error.midpointUnavailable": "midPoint didn't answer. Try again in a moment.",
  "error.hostRefused": "The assistant app didn't allow this action.",
  "status.disabled": "Turned off, not in effect",
  "status.archived": "Archived, not in effect",
  "status.personDisabled": "Account turned off",
  "status.case.waiting": "Waiting",
  "status.case.approved": "Approved",
  "status.case.rejected": "Rejected",
  "status.case.closed": "Closed",
  "status.case.withdrawn": "Withdrawn",
  "time.justNow": "just now",
  "time.minutesAgo": "{count, plural, one {# minute ago} other {# minutes ago}}",
  "time.hoursAgo": "{count, plural, one {# hour ago} other {# hours ago}}",
  "time.daysAgo": "{count, plural, one {# day ago} other {# days ago}}",
  "time.soon": "in less than a minute",
  "time.inMinutes": "{count, plural, one {in # minute} other {in # minutes}}",
  "time.inHours": "{count, plural, one {in # hour} other {in # hours}}",
  "time.inDays": "{count, plural, one {in # day} other {in # days}}",
  "time.todayAt": "today, {time}",
  "time.tomorrowAt": "tomorrow, {time}",
  "time.today": "today",
  "time.tomorrow": "tomorrow",
  "timeline.justification": "Your justification",
  "timeline.stage": "Step {number}: {who}",
  "timeline.stageNamed": "Step {number}, {name}: {who}",
  "timeline.whoAll": "{count, plural, =2 {{names}, both needed} other {{names}, all needed}}",
  "timeline.whoAny": "{names}, the first decision counts",
  "timeline.step": "Step {number}",
  "timeline.stepNamed": "Step {number}, {name}",
  "timeline.decidedBy": "Decided by {name}",
  "timeline.closedAt": "Closed {time}",
  "timeline.comment": "Comment from {name}",
  "myRequests.loading": "Loading your requests…",
  "myRequests.group.open": "Waiting",
  "myRequests.group.closed": "Finished",
  "myRequests.row.forOther": "for {user}",
  "myRequests.row.requested": "Requested {time}",
  "myRequests.row.waitingFor": "Waiting for {names}",
  "myRequests.row.closed": "Finished {time}",
  "myRequests.action.details": "Details",
  "myRequests.action.hideDetails": "Hide details",
  "myRequests.action.showAll": "Show all my requests",
  "myRequests.action.withdraw": "Withdraw",
  "myRequests.action.previewWithdraw": "Preview withdrawal",
  "myRequests.action.previewWithdrawLabel": "Preview withdrawal of your request for {role}",
  "myRequests.action.withdrawLabel": "Withdraw your request for {role}",
  "myRequests.outcome.withdrawn": "Request withdrawn. midPoint closed it.",
  "myRequests.outcome.unconfirmed": "Sent to midPoint, but the request still shows as open. Refresh to check.",
  "myRequests.empty": "You haven't made any requests.",
  "myRequests.empty.personal": "These are the requests of {name}, the account this server signs in with.",
  "validity.permanent": "No end date",
  "validity.until": "Until {date}",
  "validity.from": "From {date}",
  "validity.fromUntil": "From {from} until {to}",
  "validity.request.days": "Access for {count, plural, one {# day} other {# days}} (ends {date})",
  "validity.request.fromDays": "Access from {from} for {count, plural, one {# day} other {# days}} (ends {to})",
  "validity.request.fromNoEnd": "Access from {date}, no end date",
  "validity.request.ended": "The requested end date has passed ({date})"
};
export const text = (key, params={}) => S[key].replace(/\{(\w+)\}/g, (_, k) => params[k] ?? "");
