// Expected English catalog strings from contract sections 10.1–10.10, 10.14, 10.18; access review wording per D39 (draft.11).
export const CAT = {
  "app.title.accessReview": "My team's access",
  "header.mode.personal": "midPoint sees everything here as {name}, this server's own account.",
  "header.mode.personal.help": "This server signs in to midPoint with its configured account, so midPoint sees that account on every request, whoever is using the assistant.",
  "header.sharedCredential": "This server signs in to midPoint with a shared account, {name}, so it can't show what's yours.",
  "common.refresh": "Refresh",
  "common.refreshing": "Refreshing…",
  "common.asOf": "As of {time}",
  "common.askAssistantToRefresh": "To update this view, ask the assistant to run it again.",
  "common.readOnlyHost": "This app can show this view but not act from it. To make changes, ask the assistant.",
  "common.expand": "Expand",
  "common.collapse": "Exit full screen",
  "common.cancel": "Cancel",
  "common.showDetails": "Show technical details",
  "common.hideDetails": "Hide technical details",
  "common.showMore": "Show more",
  "common.showLess": "Show less",
  "common.andMore": "{count, plural, one {# more} other {# more}}",
  "common.whatsThis": "What's this?",
  "common.you": "you",
  "common.personHidden": "a person you can't see in midPoint",
  "common.personHiddenStart": "A person you can't see in midPoint",
  "common.itemHidden": "an item you can't see in midPoint",
  "common.request": "the request",
  "common.inherited": "Comes with other access",
  "common.inheritedVia": "Comes with {source}",
  "common.detailsTool": "Tool: {tool}",
  "common.redacted": "[address removed]",
  "common.openInMidpoint": "Open in midPoint",
  "common.openInMidpointLabel": "Open in midPoint: {name}",
  "common.openInMidpointNote": "\"Open in midPoint\" opens midPoint's own pages. You may need to sign in there, and some pages need midPoint permissions you might not have.",
  "state.slow": "Still waiting for midPoint…",
  "state.cancelled": "This request was cancelled.",
  "state.cancelledReason": "This request was cancelled: {reason}",
  "state.versionMismatch": "This view doesn't match the server's version. The server's answer is shown as text below.",
  "state.textOnly": "This answer can't be shown as a view. Here is the server's text.",
  "dryrun.banner.title": "Preview only",
  "dryrun.banner.body": "Changes are turned off on this server. Buttons show what would be sent to midPoint; nothing is changed.",
  "dryrun.submit": "Show preview",
  "dryrun.result.title": "Preview: nothing was changed",
  "dryrun.details.request": "Request that would be sent",
  "dryrun.details.summary": "Server summary: {summary}",
  "strip.source": "Reported by {source}",
  "strip.sourceUnnamed": "Reported by the connection between the assistant and midPoint",
  "strip.held.title": "Waiting for approval",
  "strip.held.body": "This action is waiting for approval by {approver}. It hasn't reached midPoint yet.",
  "strip.held.bodyNoApprover": "This action is waiting for approval. It hasn't reached midPoint yet.",
  "strip.denied.title": "Blocked",
  "strip.denied.body": "This action was blocked before it reached midPoint.",
  "strip.reason": "Reason: {reason}",
  "strip.expires": "Expires {time}",
  "strip.ref": "Reference: {ref}",
  "confirm.row.role": "Role",
  "confirm.row.for": "For",
  "confirm.row.from": "From",
  "confirm.row.request": "Request",
  "confirm.row.validity": "How long",
  "confirm.working": "Working…",
  "confirm.revoke.title": "Remove {role} from {user}?",
  "confirm.revoke.body": "{user} will lose {role} and any access that comes only from it.",
  "confirm.revoke.policy": "midPoint's policies still apply and may require an approval first.",
  "confirm.revoke.submit": "Remove role",
  "error.generic": "midPoint couldn't complete this.",
  "error.sharedCredential": "This server signs in to midPoint with a shared account, so it can't answer for you personally. Ask your midPoint administrator to set up per-person sign-in.",
  "error.notRequestable": "This role can't be requested: midPoint's catalog doesn't offer it for request.",
  "error.invalidField": "Some request details are missing or not valid. Check the marked field.",
  "error.invalidValidity": "The chosen dates aren't valid. Check how long the role should be valid and try again.",
  "error.notInInbox": "This request is no longer waiting for your decision.",
  "error.alreadyDecided": "This step of the request has already been decided.",
  "error.requestClosed": "This request is already closed: it was decided or withdrawn.",
  "error.notYourRequest": "Only the person who made a request can withdraw it.",
  "error.notAssigned": "This role is no longer directly assigned to this person.",
  "error.invalidInput": "The server rejected the request as incomplete or invalid.",
  "error.notAuthorized": "midPoint says you aren't allowed to do this.",
  "error.refused": "midPoint refused this.",
  "error.reason": "midPoint's reason: {reason}",
  "error.notFound": "midPoint couldn't find this item. It may have been deleted.",
  "error.midpointUnavailable": "midPoint didn't answer. Try again in a moment.",
  "error.hostRefused": "The assistant app didn't allow this action.",
  "status.disabled": "Turned off",
  "status.archived": "Archived",
  "status.personDisabled": "Account off",
  "time.justNow": "just now",
  "time.minutesAgo": "{count, plural, one {# minute ago} other {# minutes ago}}",
  "time.hoursAgo": "{count, plural, one {# hour ago} other {# hours ago}}",
  "time.daysAgo": "{count, plural, one {# day ago} other {# days ago}}",
  "time.soon": "in less than a minute",
  "time.inMinutes": "{count, plural, one {in # minute} other {in # minutes}}",
  "time.inHours": "{count, plural, one {in # hour} other {in # hours}}",
  "time.inDays": "{count, plural, one {in # day} other {in # days}}",
  "time.todayAt": "today, {time}",
  "time.tomorrowAt": "tomorrow, {time}",
  "time.today": "today",
  "time.tomorrow": "tomorrow",
  "review.loading": "Loading access…",
  "review.person.label": "Your team",
  "review.person.selfOption": "{name} (you)",
  "review.person.otherOption": "{name} (not your direct report)",
  "review.relation.directReport": "Reports to you",
  "review.relation.self": "This is your own access. Removing your own roles isn't offered here.",
  "review.relation.other": "You can see this person's access, but they aren't your direct report.",
  "review.section.roles": "Roles",
  "review.section.inherited": "Comes with other roles",
  "review.section.orgs": "Teams",
  "review.section.other": "Other access",
  "review.other.account": "Account in {name}",
  "review.inherited.hint": "These can't be removed on their own.",
  "review.org.manager": "Manager",
  "review.org.member": "Member",
  "review.link.approver": "Approves requests for it",
  "review.link.owner": "Owner",
  "review.role.starts": "Starts {date}",
  "review.role.endsIn": "{count, plural, =0 {Ends today} =1 {Ends tomorrow} other {Ends in # days}}",
  "review.role.since": "Since {date}",
  "review.role.until": "{first, select, yes {Until {date}} other {until {date}}}",
  "review.role.approvedBy": "{first, select, yes {Approved by {name}} other {approved by {name}}}",
  "review.role.requestedBy": "{first, select, yes {Requested by {name}} other {requested by {name}}}",
  "review.role.addedBy": "{first, select, yes {Added by {name}} other {added by {name}}}",
  "review.col.access": "Access",
  "review.col.since": "Since",
  "review.col.until": "Until",
  "review.action.revoke": "Remove",
  "review.action.revokeLabel": "Remove {role} from {user}",
  "review.action.preview": "Preview removal",
  "review.action.previewLabel": "Preview removal of {role} from {user}",
  "review.action.requestFor": "Request access for {name}",
  "review.handoff.requestFor": "Show me the roles I can request for {name}.",
  "review.empty": "{user} has no directly assigned access.",
  "review.team.noOrgs": "You don't manage a team in midPoint, so there's nobody to review here.",
  "review.team.noneVisible": "midPoint shows no one in {orgs}. You may not be allowed to see them.",
  "review.team.personalNote": "This is the team of {name}, the account this server signs in with.",
  "review.outcome.removed": "{role} was removed from {user}.",
  "review.outcome.pending": "The removal of {role} from {user} is waiting for approval in midPoint.",
  "review.outcome.stillAssigned": "midPoint accepted the change, but {user} still has {role}. A policy may have assigned it again.",
  "validity.permanent": "No end date",
  "validity.request.days": "Access for {count, plural, one {# day} other {# days}} (ends {date})",
  "validity.request.fromDays": "Access from {from} for {count, plural, one {# day} other {# days}} (ends {to})",
  "validity.request.fromNoEnd": "Access from {date}, no end date",
  "validity.request.ended": "The requested end date has passed ({date})"
};
// text fills {arg} and the select and plural forms the catalog uses (=N, one, other; # is the count).
const branches = (body) => {
  const out = {}; let i = 0;
  while (i < body.length) {
    const m = /\s*([=\w]+)\s*\{/y; m.lastIndex = i; const k = m.exec(body); if (!k) break;
    let d = 1, j = m.lastIndex; for (; j < body.length && d; j++) d += body[j] === '{' ? 1 : body[j] === '}' ? -1 : 0;
    out[k[1]] = body.slice(m.lastIndex, j - 1); i = j;
  }
  return out;
};
const format = (src, args) => {
  let out = '', i = 0;
  while (i < src.length) {
    if (src[i] !== '{') { out += src[i++]; continue; }
    let d = 1, j = i + 1; for (; j < src.length && d; j++) d += src[j] === '{' ? 1 : src[j] === '}' ? -1 : 0;
    const inner = src.slice(i + 1, j - 1), m = /^\s*(\w+)\s*,\s*(plural|select)\s*,([\s\S]*)$/.exec(inner); i = j;
    if (!m) { out += String(args[inner.trim()] ?? ''); continue; }
    const b = branches(m[3]), v = args[m[1]];
    if (m[2] === 'select') out += format(b[String(v)] ?? b.other ?? '', args);
    else out += format(b[`=${v}`] ?? (Number(v) === 1 ? b.one : undefined) ?? b.other ?? '', args).replace(/#/g, String(v));
  }
  return out;
};
export const text = (key, args = {}) => format(CAT[key], args);
